repository: shekhar-shubhendu/shekhar-shubhendu.github.io
# favicon: images/favicon.ico

name: Shubhendu Shekhar
title: Full Stack Developer
email: shubhendu.in@gmail.com
website: shubhendu.de

github_username:  shekhar-shubhendu
linkedin_username: shubhendu-shekhar

about_profile_image: images/photo.jpg
about_content: |
  Hi, My name is Shubhendu Shekhar and I'm a senior software engineer @ Ape Unit GmbH. I'm currently developing the blockchain explorer and node middleware for our client æternity and also helping their SDK and DevOps team.

  I am most skilled in: <mark>Blockchain Applications</mark> and <mark>Web Development</mark>

more_content: |
  Alongside my interests in blockchain & web development, some of my other interests and hobbies are:
   - Gaming (PS4)
   - Reading Books
   - Sleeping

  I can only speak 2 human laguages at the moment:
   - Hindi (Native)
   - English
   - Trying to learn a third (German)

  And at last few things that can be considered achievements:
  - Won first IPDB Hackathon held in Berlin @ Revision Summit 2018.
  - Runner-up of Blockchain India Week Hackathon held at IIT-Bombay.

footer_show_references: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

social:
  name: Shubhendu Shekhar
  links:
    - https://www.linkedin.com/in/shubhendu-shekhar
    - https://github.com/shekhar-shubhendu
author: shubhendu shekhar
seo:
  type: Person
