repository: shekhar-shubhendu/shekhar-shubhendu.github.io

darkmode: true

name: Shubhendu Shekhar
title: Full Stack Developer
email: connect@shubhendu.de
website: shubhendu.de

github_username: shekhar-shubhendu
linkedin_username: shubhendu-shekhar

about_profile_image: images/photo.jpg
about_content: |
  Hi, My name is Shubhendu Shekhar and I'm a Senior Software Engineer @ Adecco Technology Center, Berlin. 

  I am most skilled in: <mark>Blockchain Applications</mark> and <mark>Web Development</mark>

more_content: |
  Alongside my interests in blockchain & web development, some of my other interests and hobbies are:
   - Gaming (PS4)
   - Reading Books
   - Sleeping

  I can only speak 2 human languages at the moment:
   - Hindi (Native)
   - English
   - Trying to learn a third (German)

  And at last few things that can be considered achievements:
  - Won first IPDB Hackathon held in Berlin @ Revision Summit 2018.
  - Runner-up of Blockchain India Week Hackathon '17 @ IIT-Bombay.

footer_show_references: true

remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

author: shubhendu shekhar
seo:
  type: Person
